#!/bin/bash
# ============================================
# WALLUST TEMPLATES SETUP FIX
# ============================================
# This script creates all missing wallust templates
# Run this to fix your wallust integration
# ============================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }
print_info() { echo -e "${BLUE}→${NC} $1"; }

echo "Creating wallust template files..."
echo ""

# Create templates directory
mkdir -p "$HOME/.config/wallust/templates"
print_success "Templates directory created"

# ============================================
# Template 1: colors.sh (main colors file)
# ============================================
print_info "Creating colors.sh template..."
cat > "$HOME/.config/wallust/templates/colors.sh" << 'EOF'
#!/bin/bash
# Auto-generated by wallust

export wallpaper="{{wallpaper}}"
export background="{{background}}"
export foreground="{{foreground}}"
export cursor="{{cursor}}"

export color0="{{color0}}"
export color1="{{color1}}"
export color2="{{color2}}"
export color3="{{color3}}"
export color4="{{color4}}"
export color5="{{color5}}"
export color6="{{color6}}"
export color7="{{color7}}"
export color8="{{color8}}"
export color9="{{color9}}"
export color10="{{color10}}"
export color11="{{color11}}"
export color12="{{color12}}"
export color13="{{color13}}"
export color14="{{color14}}"
export color15="{{color15}}"
EOF
print_success "colors.sh template created"

# ============================================
# Template 2: bspwm colors
# ============================================
print_info "Creating bspwm colors template..."
cat > "$HOME/.config/wallust/templates/colors-bspwm.sh" << 'EOF'
#!/bin/bash
# BSPWM Colors - Auto-generated by wallust

bspc config normal_border_color "{{color0}}"
bspc config active_border_color "{{color2}}"
bspc config focused_border_color "{{color4}}"
bspc config presel_feedback_color "{{color1}}"
EOF
print_success "bspwm colors template created"

# ============================================
# Template 3: Polybar colors
# ============================================
print_info "Creating polybar colors template..."
cat > "$HOME/.config/wallust/templates/colors-polybar.ini" << 'EOF'
; Polybar Colors - Auto-generated by wallust

[colors]
background = {{background}}
foreground = {{foreground}}
primary = {{color4}}
secondary = {{color2}}
alert = {{color1}}
disabled = {{color8}}

; All 16 colors available
color0 = {{color0}}
color1 = {{color1}}
color2 = {{color2}}
color3 = {{color3}}
color4 = {{color4}}
color5 = {{color5}}
color6 = {{color6}}
color7 = {{color7}}
color8 = {{color8}}
color9 = {{color9}}
color10 = {{color10}}
color11 = {{color11}}
color12 = {{color12}}
color13 = {{color13}}
color14 = {{color14}}
color15 = {{color15}}
EOF
print_success "Polybar colors template created"

# ============================================
# Template 4: Rofi colors
# ============================================
print_info "Creating rofi colors template..."
cat > "$HOME/.config/wallust/templates/colors-rofi.rasi" << 'EOF'
/* Rofi Colors - Auto-generated by wallust */

* {
    background:     {{background}};
    foreground:     {{foreground}};
    selected:       {{color4}};
    active:         {{color2}};
    urgent:         {{color1}};
    
    bg:             {{background}};
    fg:             {{foreground}};
    accent:         {{color4}};
    
    color0:         {{color0}};
    color1:         {{color1}};
    color2:         {{color2}};
    color3:         {{color3}};
    color4:         {{color4}};
    color5:         {{color5}};
    color6:         {{color6}};
    color7:         {{color7}};
    color8:         {{color8}};
    color9:         {{color9}};
    color10:        {{color10}};
    color11:        {{color11}};
    color12:        {{color12}};
    color13:        {{color13}};
    color14:        {{color14}};
    color15:        {{color15}};
}
EOF
print_success "Rofi colors template created"

# ============================================
# Template 5: Dunst colors
# ============================================
print_info "Creating dunst colors template..."
cat > "$HOME/.config/wallust/templates/colors-dunst" << 'EOF'
# Dunst Configuration - Auto-generated by wallust

[global]
    frame_color = "{{color4}}"
    separator_color = "{{color8}}"

[urgency_low]
    background = "{{background}}"
    foreground = "{{foreground}}"
    frame_color = "{{color2}}"

[urgency_normal]
    background = "{{background}}"
    foreground = "{{foreground}}"
    frame_color = "{{color4}}"

[urgency_critical]
    background = "{{color1}}"
    foreground = "{{background}}"
    frame_color = "{{color1}}"
EOF
print_success "Dunst colors template created"

# ============================================
# Template 6: Alacritty colors
# ============================================
print_info "Creating alacritty colors template..."
cat > "$HOME/.config/wallust/templates/colors-alacritty.toml" << 'EOF'
# Alacritty Colors - Auto-generated by wallust

[colors.primary]
background = "{{background}}"
foreground = "{{foreground}}"

[colors.cursor]
text = "{{background}}"
cursor = "{{cursor}}"

[colors.normal]
black = "{{color0}}"
red = "{{color1}}"
green = "{{color2}}"
yellow = "{{color3}}"
blue = "{{color4}}"
magenta = "{{color5}}"
cyan = "{{color6}}"
white = "{{color7}}"

[colors.bright]
black = "{{color8}}"
red = "{{color9}}"
green = "{{color10}}"
yellow = "{{color11}}"
blue = "{{color12}}"
magenta = "{{color13}}"
cyan = "{{color14}}"
white = "{{color15}}"
EOF
print_success "Alacritty colors template created"

# ============================================
# Template 7: Tmux colors
# ============================================
print_info "Creating tmux colors template..."
cat > "$HOME/.config/wallust/templates/colors-tmux.conf" << 'EOF'
# Tmux Colors - Auto-generated by wallust

set -g status-style "bg={{background}},fg={{foreground}}"
set -g status-left-style "bg={{color4}},fg={{background}}"
set -g status-right-style "bg={{color8}},fg={{foreground}}"
set -g pane-border-style "fg={{color8}}"
set -g pane-active-border-style "fg={{color4}}"
set -g message-style "bg={{color4}},fg={{background}}"
EOF
print_success "Tmux colors template created"

# ============================================
# Template 8: Yazi colors
# ============================================
print_info "Creating yazi colors template..."
cat > "$HOME/.config/wallust/templates/colors-yazi.toml" << 'EOF'
# Yazi Colors - Auto-generated by wallust

[flavor]
use = "custom"

[flavor.custom.manager]
cwd = { fg = "{{color4}}" }
hovered = { bg = "{{color8}}", fg = "{{foreground}}" }
preview_hovered = { bg = "{{color8}}" }
find_keyword = { fg = "{{color3}}", bold = true }
find_position = { fg = "{{color5}}", bg = "reset", bold = true }
marker_copied = { fg = "{{color2}}", bg = "{{color2}}" }
marker_cut = { fg = "{{color1}}", bg = "{{color1}}" }
marker_marked = { fg = "{{color3}}", bg = "{{color3}}" }
marker_selected = { fg = "{{color4}}", bg = "{{color4}}" }
tab_active = { fg = "{{background}}", bg = "{{color4}}" }
tab_inactive = { fg = "{{foreground}}", bg = "{{color8}}" }
border_symbol = "│"
border_style = { fg = "{{color8}}" }

[flavor.custom.status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{{color8}}", bg = "{{background}}" }
mode_normal = { fg = "{{background}}", bg = "{{color4}}", bold = true }
mode_select = { fg = "{{background}}", bg = "{{color2}}", bold = true }
mode_unset = { fg = "{{background}}", bg = "{{color1}}", bold = true }

[flavor.custom.input]
border = { fg = "{{color4}}" }
title = { fg = "{{color4}}" }
value = { fg = "{{foreground}}" }
selected = { bg = "{{color8}}" }

[flavor.custom.select]
border = { fg = "{{color4}}" }
active = { fg = "{{color4}}", bold = true }
inactive = { fg = "{{foreground}}" }

[flavor.custom.completion]
border = { fg = "{{color4}}" }
active = { bg = "{{color8}}" }
inactive = { fg = "{{foreground}}" }

[flavor.custom.filetype]
rules = []
EOF
print_success "Yazi colors template created"

# ============================================
# Template 9: Neovim colors
# ============================================
print_info "Creating neovim colors template..."
cat > "$HOME/.config/wallust/templates/colors-neovim.vim" << 'EOF'
" Neovim Colors - Auto-generated by wallust

let g:terminal_color_0  = "{{color0}}"
let g:terminal_color_1  = "{{color1}}"
let g:terminal_color_2  = "{{color2}}"
let g:terminal_color_3  = "{{color3}}"
let g:terminal_color_4  = "{{color4}}"
let g:terminal_color_5  = "{{color5}}"
let g:terminal_color_6  = "{{color6}}"
let g:terminal_color_7  = "{{color7}}"
let g:terminal_color_8  = "{{color8}}"
let g:terminal_color_9  = "{{color9}}"
let g:terminal_color_10 = "{{color10}}"
let g:terminal_color_11 = "{{color11}}"
let g:terminal_color_12 = "{{color12}}"
let g:terminal_color_13 = "{{color13}}"
let g:terminal_color_14 = "{{color14}}"
let g:terminal_color_15 = "{{color15}}"

highlight Normal guibg={{background}} guifg={{foreground}}
highlight CursorLine guibg={{color8}}
highlight StatusLine guibg={{color4}} guifg={{background}}
highlight Visual guibg={{color8}}
EOF
print_success "Neovim colors template created"

# ============================================
# Fix wallust.toml configuration
# ============================================
print_info "Creating/Fixing wallust.toml..."
cat > "$HOME/.config/wallust/wallust.toml" << 'EOF'
backend = "resized"
color_space = "lab"
threshold = 1
palette_size = 16
check_contrast = true

[[template]]
template = "colors.sh"
target = "~/.config/wallust/colors.sh"

[[template]]
template = "colors-bspwm.sh"
target = "~/.config/bspwm/colors.sh"

[[template]]
template = "colors-polybar.ini"
target = "~/.config/polybar/colors.ini"

[[template]]
template = "colors-rofi.rasi"
target = "~/.config/rofi/colors.rasi"

[[template]]
template = "colors-dunst"
target = "~/.config/dunst/dunstrc"

[[template]]
template = "colors-alacritty.toml"
target = "~/.config/alacritty/colors.toml"

[[template]]
template = "colors-tmux.conf"
target = "~/.config/tmux/colors.conf"

[[template]]
template = "colors-yazi.toml"
target = "~/.config/yazi/theme.toml"

[[template]]
template = "colors-neovim.vim"
target = "~/.config/nvim/colors/wallust.vim"
EOF
print_success "wallust.toml created/fixed (threshold set to 1)"

# ============================================
# Summary
# ============================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Templates Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
print_info "All template files created in ~/.config/wallust/templates/"
print_info "wallust.toml configured with proper template targets"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Test wallust: wallust run ~/Pictures/Wallpapers/yourimage.png"
echo "  2. Use your cwal script: cwal ~/Pictures/Wallpapers/yourimage.png"
echo "  3. Or use random: cwal --random"
echo ""
echo -e "${BLUE}Generated files will appear in:${NC}"
echo "  • ~/.config/wallust/colors.sh"
echo "  • ~/.config/bspwm/colors.sh"
echo "  • ~/.config/polybar/colors.ini"
echo "  • ~/.config/rofi/colors.rasi"
echo "  • ~/.config/dunst/dunstrc"
echo "  • ~/.config/alacritty/colors.toml"
echo "  • ~/.config/tmux/colors.conf"
echo "  • ~/.config/yazi/theme.toml"
echo "  • ~/.config/nvim/colors/wallust.vim"
echo ""
